# configs/parameters.yml

files:
  food_drive_2023: "data/raw/Food Drive Data Collection 2023.csv"
  food_drive_2024: "data/raw/Food Drive Data Collection 2024.csv"
  edmonton_geo: "data/external/City_of_Edmonton_-_Neighbourhoods__Centroid_Point.csv"
  train_config: "configs/train_config.yaml"
  model: "models/polynomial_regression_model.pkl"
  cleaned_data: "data/processed/EFD_Cleaned_dataset.csv"
results:
  evaluation: "predict/evaluation.png"
dvc:
  gdrive_url: gdrive://15yBJ9o3KPb-19LBQsfuEh66eGCLCO1Kp
  gdrive_client_id: 274368669839-8aaqvd3tttvukus4otp9ni6mn3aacu7a.apps.googleusercontent.com
  gdrive_client_secret: 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
