# configs/parameters.yml

files:
  food_drive_2023: "data/raw/Food Drive Data Collection 2023.csv"
  food_drive_2024: "data/raw/Food Drive Data Collection 2024.csv"
  edmonton_geo: "data/external/City_of_Edmonton_-_Neighbourhoods__Centroid_Point.csv"
  train_config: "configs/train_config.yaml"
  model: "models/polynomial_regression_model.pkl"
  cleaned_data: "data/processed/EFD_Cleaned_dataset.csv"
results:
  evaluation: "predict/evaluation.png"
dvc:
  gdrive_url: blank
  gdrive_client_id: blank
  gdrive_client_secret: blank
setup:
  allow_data_file_track: "Off"
  allow_ml_model_track: "On"
  mlflow_experiment_name: "EFD 2024 Model Experiment"
  mlflow_experiment_url: "http://localhost:8080/"